spring.application.name=tagua

# Lê variáveis locais do arquivo .env (que NÃO vai pro GitHub)
spring.config.import=optional:file:.env[.properties]

# MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/duvidasdb
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
